CV1={"NAME":"AHMET ATES","AGE":"26","JOB TİTLE":"DEVELOPER","UNIVERSITY":"HACETTEPE","ADRESS":"İSTANBUL"}
CV2={"NAME":"AYKUT ALDAG","AGE":"28","JOB TİTLE":"TEACHER","UNIVERSITY":"METU","ADRESS":"ANKARA"}
CV3={"NAME":"İLYAZ BOZYEL","AGE":"23","JOB TİTLE":"ARCHITECH","UNIVERSITY":"CAMBRIDGE","ADRESS":"İZMİR"}
CV4={"NAME":"RABİA OZDAG","AGE":"24","JOB TİTLE":"DOCTOR","UNIVERSITY":"YTU","ADRESS":"ADANA"}
CV5={"NAME":"MUSTAFA CINAR","AGE":"45","JOB TİTLE":"UNEMPLOYED","UNIVERSITY":"HIGH SCHOOL","ADRESS":"İSTANBUL"}
print(CV1,'\n',CV2,'\n',CV3,'\n',CV4,'\n',CV5)
